# Form implementation generated from reading ui file 'C:\lms\coffee\UI\addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.roastEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.roastEdit.setObjectName("roastEdit")
        self.verticalLayout.addWidget(self.roastEdit)
        self.groundCheck = QtWidgets.QCheckBox(parent=AddEditCoffeeForm)
        self.groundCheck.setObjectName("groundCheck")
        self.verticalLayout.addWidget(self.groundCheck)
        self.descriptionEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout.addWidget(self.descriptionEdit)
        self.priceEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.priceEdit.setObjectName("priceEdit")
        self.verticalLayout.addWidget(self.priceEdit)
        self.volumeEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.volumeEdit.setObjectName("volumeEdit")
        self.verticalLayout.addWidget(self.volumeEdit)
        self.saveButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.groundCheck.setText(_translate("AddEditCoffeeForm", "Молотый"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
